### ISSUE TITLE
Need help please . Stuck on booting 

### ISSUE THREAD

**Issue by IbragimGorch** [anjomro/kobra-unleashed#12]
Hi! Much appreciate all of work and instructions thank you! 
I was going through readme trying to make web server. Everything was going well and on the step where you need to change App file and change anycubic cloud domain names to my server something gone wrong. 
I had root access. After opening app/app file i searched for mqtts://anycubic domains and found like 3-4 of them. I changed ot all to my server ip and tried to save changes and it said that file is busy and can not save changes. Then I found app/app process and "kill [pid]" closed it. I have successfully changed anycubic domains to server ip and rebooted my kobra 2 plus. And it got stuck on boot. It doesn't even try to start booting and got nothing in console (usb-uart). After that I realized that i did all backups on printer and didn't saved it anywhere else. Now i can boot it in FEL mode and connect from laptop but i don't have emmc backup. Maybe someone can share his emmc backup file? or maybe anyone know a solution how to make it boot up again

**Comment by AGG2017** [comment]
That was the wrong way to modify the app file. When killing the app, the watch dog will be activated and it will reboot the printer in few seconds. If in this time you try to write something to the emmc during started reboot, you may corrupt the file system. The right way is to make a copy of /app/app to somewhere else like /user/app, then to modify /user/app, and then to copy /user/app to /app/app, and then to reboot to take effect.
Now from FEL you have to use the modified xfel tool to be able to write to the emmc. You need also to have at least the master boot record, and the first 11 partitions. Unfortunately, I don't have Plus backup, only Pro and it is with modified partition size of 1GB each to install larger packages, so it will be not useful for you. But any other original backup can be used, then update with your Plus fw to make it Plus (mostly the app file is different), and copy the default printer_plus.cfg to the /user folder, and then start leveling, etc. set it properly. Use the tools from this repo:

https://github.com/ultimateshadsform/Anycubic-Kobra-2-Series-Tools

**Comment by IbragimGorch** [comment]
Thank you for response! Really appreciate it!
Yeah, I only saw the right way to do it in instructions after i bricked my printer( Got to be more careful 
By default back up do you mean to ask someone to share back up made with emmc_backup procedure? or i can use firmware from repos? I'm really sorry for stupid questions,  it's my first printer and I'm into 3d printing just for 3 weeks now

**Comment by AGG2017** [comment]
The firmware that you download requires your printer to be able to boot and it does not reload all emmc partitions, just a few of them. In order to be sure your printer is completely restored, you need to find someone with Plus printer to execute emmc backup (all 12 emmc partitions, about 8GB file) or at least emmc system backup (first 11 partitions, about 560MB file). I recommend to use system backup and then system restore because full backup and restore by xfel in FEL mode will take many hours to complete. You don't need to restore the last partition because it is used for logs and copy of the gcode files, so nothing important to need backup/restore but it takes many hours to do it.
In case you cannot find Plus backup I can try to find original Pro backup but then you need to upgrade it with Plus firmware and to restore the printer_plus.cfg file becase the configuration will be for smaller printer.
There is a way from FEL mode to extract only the /user partifion (most likely it is not corrupted) by xfel tool before doing any attempt to restore anything, and then to mount it on a linux computer to extract your original mqtt keys, configuration and all important files there. Then, when you restore your printer from any backup and copy all the files from your original /user partition, it will be easy to restore your setup from any backup.

**Comment by anjomro** [comment]
Thanks @AGG2017 for your support.

I'm very sorry that your printer is bricked @IbragimGorch 
The explanation of @AGG2017 sounds plausible, that some file corruption happened. I hope you can restore your printer. I can't help you much out there since I have not used xfel yet. @AGG2017 and  @ultimateshadsform may be able to give some pointers.

I would say not knowing much about 3D printing doesn't matter much here, it's more important to have a good grasp on Linux in constrained environments.

**Comment by ultimateshadsform** [comment]
The printers usually have 2 filesystems just because of stuff like this.

So if you're lucky you can just use uboot to switch filesystems.

Change envs to be the other partition.

In the env there should be rootfsa and rootfsb etc. Depending on which one you are on you will need to switch to the other one and you may have it working again.

And if you manage to make it working again then update so you override the broken "partition" and then do a proper backup.

There are some instructions already on how to enter uboot.
U-boot should boot before the kernel and stuff so try holding the S key while booting via uart.

**Comment by AGG2017** [comment]
Most likely he is using some latest firmware (3.xx) that has the uboot console disabled. Also it is unknown where are the corrupted sectors. A/B file systems are switched only during normal update and the writing is done only on the next unused partition. He did emmc writing during reboot process already started, and the writing may affect any emmc sector on any partition. The most reliable way is to extract the original /user partition and to restore all partitions from another Pro/Plus/Max backup with xfel, then to upgrade with Plus firmware to make it Plus if not restored from Plus, then to restore the original /user files. This must work in any damages over the entire emmc.

Partial partition restore or partition switch is possible when you are able to figure out what is working and what not, but with much more knowledge about this particular printer model which is not his case.

**Comment by IbragimGorch** [comment]
Thanks a lot guys! 


> There is a way from FEL mode to extract only the /user partifion (most likely it is not corrupted) by xfel tool

@AGG2017 I've tried to google how to do it, but couldn't find any info. Can you please tell me how to do it?  


> There are some instructions already on how to enter uboot.

@ultimateshadsform I already tried to follow instructions in [Anycubic-Kobra-2-Series-Tools](https://github.com/ultimateshadsform/Anycubic-Kobra-2-Series-Tools/tree/main) repo in EMMC_RESTORE, but it won't work

 
![photo_2024-05-08_19-09-09](https://github.com/anjomro/kobra-unleashed/assets/68636926/f48f9730-10cd-4824-8886-ac9204b250ab)
![photo_2024-05-08_19-09-10](https://github.com/anjomro/kobra-unleashed/assets/68636926/afeee9a2-2eaa-4bd9-bc45-3ced5bbd9d1c)

It's looks like it doesn't even try to start ubooting. 



> Most likely he is using some latest firmware (3.xx) that has the uboot console disabled.

Before starting with web server i downgraded firmware to 2.3.9 and was able to access uboot console. I got permanent root access and ssh connection. Right now I'm connected to printer with UART-USB and USB A - USB A (male-male). 

![photo_2024-05-08_19-09-10 (2)](https://github.com/anjomro/kobra-unleashed/assets/68636926/f3ad11bb-06a0-4851-81af-4ab11cd74814)
  
I asked in telegram channel for backup and one great guy said that he can do it later! 
I'll try to perform EMMC_RESTORE instruction if i got backup

**Comment by ultimateshadsform** [comment]
Yeah hope it all goes well!

We recommend using the custom firmware that enables uart in later versions.

**Comment by AGG2017** [comment]
> > There is a way from FEL mode to extract only the /user partifion (most likely it is not corrupted) by xfel tool
> 
> @AGG2017 I've tried to google how to do it, but couldn't find any info. Can you please tell me how to do it?

`xfel extra sdmmc read <address> <length> <file>` - Used to read emmc to file, adrress and length are is bytes, sector based (512 bytes)

Before this command you may want to check if the FEL mode is selected, and the connection to the printer is well done by:

`xfel extra sdmmc detect`

The /user partition is emmc partition 11 that starts from sector 0xd4b84 and ends on sector 0x114c3f. So, 0xd4b84 is 871300 decimal sector and multiplied by 512 bytes per sector is giving you a start address of 446105600. The length of the partition is 0x114c3f - 0xd4b84  + 1, or 0x400bc, or 262332 decimal sectors, or 134313984 bytes (multiplied by 512).

So, the xfel command to backup the /user partition should be:

`xfel extra sdmmc read 446105600 134313984 partition11.img`

Use the xfel tool from the tools repo, not the original one because this modified version is only able to read/write from the emmc.

Then, mount this partition on a linux machine (it is ext4 file system) and you will have access to all the files needed to restore later on a working printer in the /user folder.

**Comment by IbragimGorch** [comment]
Thanks a lot!
I have backup.bin that Mi from telegram channel shared with me , much thanks to him!
And i managed to extract /user folder from my printer. 
I did restored with backup and it worked. Than i tried to upgrade to modified firmware (using Anycubic tools repo) and it's again not booting. Restore case a ,b doesn't work for me. I don't really know what I'm doing wrong , I only modified App to refer to my local server. 
Also now i can't restore , because while using command xfel extra sdmmc write 0 backup.bin (case c) I'm getting error writing data after few seconds at 1%, 0% (always different). Coulb it be faulty emmc ai my printer? or just my PC or cabel 
Can I somehow write only "app" to stock one? I don't know how to get address for that

**Comment by IbragimGorch** [comment]
Also it'll be really really great if you could find original backup for me

**Comment by IbragimGorch** [comment]
Thank you so much guys! 
It's all perfect now with a great help of Mi from telegram channel and Assen and everyone here! 
The work that you've done is just unbelievable! If you need anything just ping me. And ,guys, provide link for donations :)
